app = "moviestream-backend"

[build]
  dockerfile = "Dockerfile"

[env]
  TMDB_API_KEY = "2088d0842ecf8d9ea2ab1e739fb9e8db"
  FRONTEND_ORIGIN = "https://moviestream-frontend.fly.dev"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]